# Generated by Django 4.2.27 on 2026-01-18 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('work_hours', models.FloatField(default=0)),
                ('overtime', models.FloatField(default=0)),
                ('undertime', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('HALF', 'Half Day'), ('ABSENT', 'Absent')], default='ABSENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='attendance__date_337b1d_idx'), models.Index(fields=['employee', 'date'], name='attendance__employe_b6a945_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
