# Generated by Django 4.2.27 on 2026-01-18 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('total_work_hours', models.FloatField(default=0)),
                ('total_overtime', models.FloatField(default=0)),
                ('total_undertime', models.FloatField(default=0)),
                ('present_days', models.IntegerField(default=0)),
                ('half_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_summaries', to='employees.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['month'], name='payroll_pay_month_7cde0d_idx'), models.Index(fields=['employee', 'month'], name='payroll_pay_employe_47bb63_idx')],
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
